//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.API.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
