//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.API.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int Id { get; set; }
        public Nullable<int> User1 { get; set; }
        public Nullable<int> User2 { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
    
        public virtual UserProfile UserProfile2 { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
