//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.API.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int Id { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public bool Status { get; set; }
    
        public virtual UserProfile FromUser { get; set; }
        public virtual UserProfile ToUser { get; set; }
    }
}
